// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyC_1R9QFdq5zU8Akx0DCsEYv59-wi9U',
    appId: '1:577144537902:web:c5bc3eed640286cadcf0bf',
    messagingSenderId: '577144537902',
    projectId: 'condominioflutter',
    authDomain: 'condominioflutter.firebaseapp.com',
    storageBucket: 'condominioflutter.firebasestorage.app',
    measurementId: 'G-K5QED45XC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVlYt0kPX4HPZL6zPy9G5zzVu_qbpDCc',
    appId: '1:577144537902:android:89b04adc085bebf8dcf0bf',
    messagingSenderId: '577144537902',
    projectId: 'condominioflutter',
    storageBucket: 'condominioflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM3Bjc3XIJElo50lrxViGeFe1jwA9DkfE',
    appId: '1:577144537902:ios:0239a56f8e74899fdcf0bf',
    messagingSenderId: '577144537902',
    projectId: 'condominioflutter',
    storageBucket: 'condominioflutter.firebasestorage.app',
    iosBundleId: 'com.example.portariaCondominio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM3Bjc3XIJElo50lrxViGeFe1jwA9DkfE',
    appId: '1:577144537902:ios:0239a56f8e74899fdcf0bf',
    messagingSenderId: '577144537902',
    projectId: 'condominioflutter',
    storageBucket: 'condominioflutter.firebasestorage.app',
    iosBundleId: 'com.example.portariaCondominio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLyC_1R9QFdq5zU8Akx0DCsEYv59-wi9U',
    appId: '1:577144537902:web:c7d61d3a4c4c9b2ddcf0bf',
    messagingSenderId: '577144537902',
    projectId: 'condominioflutter',
    authDomain: 'condominioflutter.firebaseapp.com',
    storageBucket: 'condominioflutter.firebasestorage.app',
    measurementId: 'G-VZZNRC8BPG',
  );
}
