const Map<String, String> localizedPt = {
  'login_title': 'Login',
  'username': 'Usuário',
  'password': 'Senha',
  'login_button': 'Entrar',
  'settings': 'Configurações',
  'language': 'Idioma',
  'theme': 'Tema',
  'dark_mode': 'Modo Escuro',
  'light_mode': 'Modo Claro',
  'search_address': 'Buscar endereço...',
  'no_residents_found': 'Nenhum morador encontrado.',
  'map_title': 'Mapa',
  'home_title': 'Início',
  'residents': 'Moradores',
  'providers': 'Prestadores',
  'visits': 'Visitas',
  'orders': 'Pedidos',
  'notifications': 'Notificações',
  'map': 'Mapa',
  'chat': 'Chat',
  'user_role': 'Morador',
  'cpf': 'CPF',
  'logout': 'Sair',
  'delete_confirmation': 'Digite "excluir" para confirmar.',
  'delete': 'Excluir',
  'edit': 'Editar',
  'save': 'Salvar',
  'cancel': 'Cancelar',
  'no_results_found': 'Nenhum resultado encontrado.',
  'call': 'Ligar',
  'message': 'Mensagem',
  'whatsapp': 'WhatsApp',
  'menu': 'Menu',
  'add': 'Adicionar',
  'confirm': 'Confirmar',
};
