class AppLocalizationsPt {
  static const Map<String, String> values = {
    // App
    'app_name': 'Portaria Condomínio',
    
    // Auth
    'login': 'Login',
    'register': 'Cadastro',
    'email': 'Email',
    'password': 'Senha',
    'confirm_password': 'Confirmar Senha',
    'forgot_password': 'Esqueceu a senha?',
    'login_error': 'Erro ao fazer login',
    'register_error': 'Erro ao fazer cadastro',
    'welcome': 'Bem-vindo',
    'login_to_continue': 'Faça login para continuar',
    'login_button': 'Entrar',
    'enable_biometric': 'Habilitar login com biometria',
    'biometric_not_available': 'Biometria não disponível neste dispositivo',
    'biometric_auth_reason': 'Autentique-se para acessar o aplicativo',
    'credentials_not_found': 'Credenciais não encontradas. Faça login primeiro',
    'biometric_auth_error': 'Erro na autenticação biométrica',
    'login_first': 'Faça login primeiro antes de habilitar a biometria',
    'fill_credentials': 'Preencha email e senha antes de habilitar a biometria',
    'user_not_recognized': 'Usuário não reconhecido',
    'enter_email': 'Por favor, insira seu email',
    'enter_password': 'Por favor, insira sua senha',
    
    // Settings
    'settings': 'Configurações',
    'language': 'Idioma',
    'theme': 'Tema',
    'dark_mode': 'Modo Escuro',
    'light_mode': 'Modo Claro',
    'system_mode': 'Modo do Sistema',
    
    // Theme names
    'blue': 'Azul',
    'red': 'Vermelho',
    'green': 'Verde',
    'purple': 'Roxo',
    'orange': 'Laranja',
    'pink': 'Rosa',
    'grey': 'Cinza',
    'brown': 'Marrom',
    'deep_purple': 'Roxo Escuro',
    'indigo': 'Índigo',
    'teal': 'Verde-azulado',
    'cyan': 'Ciano',
    'light_blue': 'Azul Claro',
    'light_green': 'Verde Claro',
    'lime': 'Lima',
    'yellow': 'Amarelo',
    'amber': 'Âmbar',
    'deep_orange': 'Laranja Escuro',
    'blue_grey': 'Cinza Azulado',
    'warm': 'Cores Quentes',
    'nature': 'Natureza',
    
    // Main navigation
    'home_title': 'Início',
    'residents': 'Moradores',
    'providers': 'Prestadores',
    'visits': 'Visitas',
    'orders': 'Encomendas',
    'notifications': 'Notificações',
    'map': 'Mapa',
    
    // Common fields
    'name': 'Nome',
    'cpf': 'CPF',
    'phone': 'Telefone',
    'address': 'Endereço',
    'apartment': 'Apartamento',
    'apartment_required': 'Apartamento é obrigatório',
    'observations': 'Observações',
    'title': 'Título',
    'description': 'Descrição',
    'status': 'Status',
    'resident': 'Morador',
    'resident_required': 'Selecione um morador',
    
    // Map features
    'map_title': 'Mapa',
    'search_address': 'Buscar endereço...',
    
    // Residents
    'no_residents_found': 'Nenhum morador encontrado',
    'user_role': 'Morador',
    'call': 'Ligar',
    'message': 'Mensagem',
    'whatsapp': 'WhatsApp',
    'edit': 'Editar',
    'delete': 'Excluir',
    'confirm_delete': 'Confirmar Exclusão',
    'delete_resident_confirmation': 'Tem certeza que deseja excluir este morador?',
    'resident_deleted': 'Morador excluído com sucesso!',
    'error_deleting_resident': 'Erro ao excluir morador',
    
    // Resident Registration
    'add_resident': 'Cadastrar Morador',
    'edit_resident': 'Editar Morador',
    'name_required': 'Informe o nome',
    'cpf_required': 'Informe o CPF',
    'phone_required': 'Informe o telefone',
    'address_required': 'Informe o endereço',
    'email_required': 'Informe o email',
    'password_required': 'Informe a senha',
    'save_changes': 'Salvar Alterações',
    'resident_updated': 'Morador atualizado com sucesso!',
    'resident_registered': 'Morador cadastrado com sucesso!',
    
    // Visits
    'add_visit': 'Adicionar Visita',
    'edit_visit': 'Editar Visita',
    'expected_date': 'Data Prevista',
    'date_required': 'Informe a data prevista',
    'expected_time': 'Hora Prevista',
    'time_required': 'Informe a hora prevista',
    'confirm_visit_deletion': 'Tem certeza que deseja excluir a visita de {name}?',
    'visit_deleted_successfully': 'Visita excluída com sucesso',
    'error_deleting_visit': 'Erro ao excluir visita',
    'visit_updated': 'Visita atualizada com sucesso',
    'visit_added': 'Visita adicionada com sucesso',
    'error_adding_visit': 'Erro ao adicionar visita',
    'error_updating_visit': 'Erro ao atualizar visita',
    'visit_details': 'Detalhes da Visita',
    'no_visits_found': 'Nenhuma visita encontrada',
    
    // Visit status
    'entry_allowed': 'Entrada liberada',
    'scheduled': 'Agendada',
    'in_progress': 'Em andamento',
    'completed': 'Concluída',
    'cancelled': 'Cancelada',
    'realized': 'Realizada',
    'unknown_status': 'Status desconhecido',
    
    // Visit actions
    'allow_entry': 'Liberar entrada',
    'revoke_entry': 'Revogar entrada',
    'entry_revoked': 'Entrada revogada',
    'error_allowing_entry': 'Erro ao liberar entrada',
    'error_revoking_entry': 'Erro ao revogar entrada',
    
    // General actions
    'logout': 'Sair',
    'delete_confirmation': 'Digite "excluir" para confirmar',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'add': 'Adicionar',
    'confirm': 'Confirmar',
    
    // Notifications
    'send_notification': 'Enviar Notificação',
    'new_notification': 'Nova Notificação',
    'add_notification': 'Adicionar Notificação',
    'notification_sent': 'Notificação enviada com sucesso!',
    'notification_marked_as_read': 'Notificação marcada como lida',
    'notification_marked_as_unread': 'Notificação marcada como não lida',
    'no_notifications': 'Nenhuma notificação encontrada',
    'fill_all_fields': 'Preencha todos os campos',
    'error': 'Erro',
    'mark_as_read': 'Marcar como lida',
    'mark_as_unread': 'Marcar como não lida',
    'delete_notification': 'Excluir notificação',
    'delete_notification_confirmation': 'Tem certeza que deseja excluir esta notificação?',
    'notification_deleted': 'Notificação excluída com sucesso',
    'error_deleting_notification': 'Erro ao excluir notificação',
    'error_updating_notification': 'Erro ao atualizar notificação',
    'error_sending_notification': 'Erro ao enviar notificação',
    'read': 'Lida',
    'unread': 'Não lida',
    'notification_status': 'Status da notificação',
    
    // Service Providers
    'service_providers': 'Prestadores de Serviço',
    'add_service_provider': 'Adicionar Prestador',
    'edit_service_provider': 'Editar Prestador',
    'service_provider_added': 'Prestador adicionado com sucesso',
    'service_provider_updated': 'Prestador atualizado com sucesso',
    'error_adding_service_provider': 'Erro ao adicionar prestador',
    'error_updating_service_provider': 'Erro ao atualizar prestador',
    'company': 'Empresa',
    'company_required': 'Empresa é obrigatória',
    
    // Chat
    'chats': 'Conversas',
    'no_chats': 'Nenhuma conversa iniciada',
    'start_new_chat': 'Iniciar nova conversa',
    'chat_select_residents': 'Moradores',
    'chat_select_providers': 'Prestadores',
    'chat_no_residents': 'Nenhum morador encontrado',
    'chat_no_providers': 'Nenhum prestador encontrado',
    
    // QR Code
    'generate_qr_code': 'Gerar QR Code',
    'view_qr_code': 'Visualizar QR Code',
    'qr_code_title': 'QR Code de Acesso',
    'house_number': 'Número da Casa',
    'visitor': 'Visitante',
    'qr_code_reader': 'Leitor QR Code',
    'scan_qr_code': 'Escanear QR Code',
    'qr_code_success': 'QR Code lido com sucesso',
    'qr_code_error': 'Erro ao ler QR Code',
    'invalid_qr_code': 'QR Code inválido',
    
    // Others
    'no_results_found': 'Nenhum resultado encontrado',
    'menu': 'Menu',
    'profile': 'Perfil',
  };
}
