const Map<String, String> localizedEn = {
  'login_title': 'Login',
  'username': 'Username',
  'password': 'Password',
  'login_button': 'Login',
  'settings': 'Settings',
  'language': 'Language',
  'theme': 'Theme',
  'dark_mode': 'Dark Mode',
  'light_mode': 'Light Mode',
  'search_address': 'Search address...',
  'no_residents_found': 'No residents found.',
  'map_title': 'Map',
  'home_title': 'Home',
};
