const Map<String, String> localizedEn = {
  'login_title': 'Login',
  'username': 'Username',
  'password': 'Password',
  'login_button': 'Login',
  'settings': 'Settings',
  'language': 'Language',
  'theme': 'Theme',
  'appearance': 'Appearance',
  'theme_default_light': 'Default Light',
  'theme_default_dark': 'Default Dark',
  'theme_indigo_light': 'Indigo Light',
  'theme_indigo_dark': 'Indigo Dark',
  'theme_teal_light': 'Teal Light',
  'theme_teal_dark': 'Teal Dark',
  'theme_orange_light': 'Orange Light',
  'theme_orange_dark': 'Orange Dark',
  'search_address': 'Search address...',
  'no_residents_found': 'No residents found.',
  'map_title': 'Map',
  'home_title': 'Home',
  'residents': 'Residents',
  'providers': 'Providers',
  'visits': 'Visits',
  'orders': 'Orders',
  'notifications': 'Notifications',
  'map': 'Map',
  'chat': 'Chat',
  'user_role': 'Resident',
  'cpf': 'CPF',
  'logout': 'Logout',
  'delete_confirmation': 'Type "delete" to confirm.',
  'delete': 'Delete',
  'edit': 'Edit',
  'save': 'Save',
  'cancel': 'Cancel',
  'no_results_found': 'No results found.',
  'call': 'Call',
  'message': 'Message',
  'whatsapp': 'WhatsApp',
  'menu': 'Menu',
  'add': 'Add',
  'confirm': 'Confirm',
};
